name: Golang CI
permissions:
  contents: read

on:
  push:
    branches: [main, develop]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main, develop]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

env:
  GO_MODULE: https://github.com/opendefensecloud/testkit
  GO_VERSION: 1.25.7

jobs:
  lint:
    runs-on: arc-scale-set
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: lint-license-and-shell
        run: |
          make lint-no-golangci
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9

  test:
    needs: lint
    runs-on: arc-scale-set
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: test
        run: make test
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.7
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
